### ISSUE TITLE
[dnsmasq] chown: unknown user/group nobody:nobody

### ISSUE THREAD

**Issue by harryboo** [Freetz-NG/freetz-ng#353]
I have made an actual version of freetz for 7490.

on 2 of 5 updated machines i see this message in MOD-LOGS.
DNSMASQ works as i can see.

![modlogs](https://user-images.githubusercontent.com/14336586/126365691-4d9552e0-3bbb-489e-a50d-feb981f5579f.png)

**Comment by fda77** [comment]
Dnsmasq created this user if it does not exist: https://github.com/Freetz-NG/freetz-ng/blob/master/make/dnsmasq/files/root/etc/init.d/rc.dnsmasq#L102
But dnsmasq is started automatically before multid and maybe avm deletes the user again... Avm does not know how useres are created on linux and just replaces the whole passwd file like a beginner
You could check /etc/passwd and `/var/log/freetz.log` to have a timeline. Users are loaded by Freetz in MODLOAD since a short time

**Comment by fda77** [comment]
As it occured only 1 time for 1 person it should not matter
